version: '3'
services:
  dns-proxy:
    image: ${OWNER}/${REPO}:${VERSION}
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    restart: unless-stopped
    tty: true
    privileged: true
    environment:
      WAN: ${WAN}
      DNSPORT: ${DNSPORT}
